'use strict';
const CONFIG = {
  // Session timing
  SESSION_DURATION_SECONDS: 90,
  FORK_TRUCK_GRACE_PERIOD_MS: 8000,
  TUGGER_GRACE_PERIOD_MS: 10000,
  JOB_WAVE_ESCALATION_SEC: 30,
  FORK_TRUCK_MIN_SPAWN_INTERVAL_MS: 5000,
  TUGGER_MIN_SPAWN_INTERVAL_MS: 5000,
  FORK_TRUCK_MAX_SPAWN_INTERVAL_MS: 6000,
  TUGGER_MAX_SPAWN_INTERVAL_MS: 6000,
  FORK_TRUCK_JOB_RATE_MULTIPLIER: 1.0,  // < 1 = faster jobs
  TUGGER_JOB_RATE_MULTIPLIER: 1.0,

  // Robot speeds in METERS PER SECOND (1 cell = 1 meter)
  FORK_TRUCK_BASE_SPEED: 10.0,
  TUGGER_BASE_SPEED: 10.0,
  HALLWAY_CONGESTION_SPEED_MULTIPLIER: 0.2,

  // Robot action durations
  PICKUP_DURATION_SEC: 0.1,
  DROPOFF_DURATION_SEC: 0.1,

  // Fleet counts
  FORK_TRUCK_COUNT: 3,
  TUGGER_COUNT: 3,

  // Orchestration (Mode 3)
  FORK_TRUCK_RESERVATION_WINDOW_MS: 8000,
  FORK_TRUCK_READY_RESERVE_COUNT: 1,
  TUGGER_DISPATCH_HOLD_BUFFER_MS: 6000,
  STAGING_AREA_MAX_HOLD_MS: 15000,

  // Scoring
  CARS_PER_MINUTE_RATE: 60,
  CONGESTION_EVENT_THRESHOLD_MS: 500,

  // Display (set at boot)
  CELL_PX: 28,         // pixels per meter/cell — recomputed at boot
  JOB_PANEL_PX: 160,  // width of right-side job panel in pixels
  SHOW_GRID_LINES: true,
};
